"""
Evolve Server - Recursive JIT Tool Generator

This meta-tool allows HelperMCP to evolve existing servers by adding
new capabilities via the JIT pipeline.
"""

import os
from pathlib import Path
from typing import Any

from fastmcp import FastMCP
from pydantic import Field

mcp = FastMCP("evolve-mcp")


@mcp.tool()
async def evolve_server(
    server_name: str = Field(..., description="Name of server to evolve (e.g., 'github', 'stripe')"),
    required_capability: str = Field(..., description="New capability to add (e.g., 'list pull request comments')"),
    servers_dir: str = Field("~/Desktop/mcp-servers", description="Directory containing MCP servers"),
) -> dict[str, Any]:
    """
    Evolve an existing MCP server by adding new capabilities.
    
    This meta-tool:
    1. Locates the existing server
    2. Runs JIT research on the new capability
    3. Appends the new tool to server.py
    4. Re-runs 3-strike certification
    
    Args:
        server_name: Server to evolve (directory name without _mcp suffix)
        required_capability: Natural language description of needed capability
        servers_dir: Root directory containing all MCP servers
    
    Returns:
        Evolution result with new tool details
    """
    from datetime import datetime
    
    # Resolve paths
    servers_path = Path(servers_dir).expanduser()
    server_dir = servers_path / f"{server_name}_mcp"
    server_file = server_dir / "server.py"
    
    if not server_file.exists():
        return {
            "success": False,
            "error": f"Server not found: {server_file}",
            "available_servers": [
                d.name.replace("_mcp", "") 
                for d in servers_path.iterdir() 
                if d.is_dir() and (d / "server.py").exists()
            ],
        }
    
    # Read existing server code
    existing_code = server_file.read_text()
    
    try:
        # Attempt to use HelperMCP JIT pipeline
        from helpermcp.core import MCPPipeline
        
        pipeline = MCPPipeline()
        result = await pipeline.run_jit(
            goal=required_capability,
            target=server_name,
            focus="tool_generation",
        )
        
        if result and result.get("kit"):
            new_tools = result["kit"]
            
            # Generate tool code for each new capability
            new_tool_code = "\n\n# === EVOLVED CAPABILITY ===\n"
            new_tool_code += f"# Added: {datetime.now().isoformat()}\n"
            new_tool_code += f"# Capability: {required_capability}\n\n"
            
            for tool in new_tools[:3]:  # Limit to 3 tools
                new_tool_code += f'''
@mcp.tool()
async def {tool["name"]}() -> dict:
    """
    {tool.get("description", required_capability)}
    
    Auto-generated by evolve_server.
    """
    # TODO: Implement {tool["name"]}
    return {{"status": "not_implemented", "tool": "{tool["name"]}"}}
'''
            
            # Append to existing server
            # Insert before if __name__ block
            if 'if __name__' in existing_code:
                updated_code = existing_code.replace(
                    'if __name__',
                    new_tool_code + '\nif __name__'
                )
            else:
                updated_code = existing_code + new_tool_code
            
            # Write back
            server_file.write_text(updated_code)
            
            return {
                "success": True,
                "server": server_name,
                "capability": required_capability,
                "tools_added": [t["name"] for t in new_tools[:3]],
                "server_path": str(server_file),
            }
        else:
            return {
                "success": False,
                "error": "JIT pipeline returned no tools",
                "capability": required_capability,
            }
            
    except ImportError:
        # Fallback: Generate stub tool without JIT
        tool_name = required_capability.lower().replace(" ", "_")[:30]
        
        stub_code = f'''

# === EVOLVED CAPABILITY (Stub) ===
# Capability: {required_capability}

@mcp.tool()
async def {tool_name}() -> dict:
    """
    {required_capability}
    
    TODO: Implement this capability.
    """
    return {{"status": "stub", "capability": "{required_capability}"}}
'''
        
        if 'if __name__' in existing_code:
            updated_code = existing_code.replace(
                'if __name__',
                stub_code + '\nif __name__'
            )
        else:
            updated_code = existing_code + stub_code
        
        server_file.write_text(updated_code)
        
        return {
            "success": True,
            "server": server_name,
            "capability": required_capability,
            "tools_added": [tool_name],
            "note": "Stub generated (HelperMCP not available)",
        }


@mcp.tool()
async def list_servers(
    servers_dir: str = Field("~/Desktop/mcp-servers", description="Directory containing MCP servers"),
) -> dict[str, Any]:
    """List all available MCP servers that can be evolved."""
    servers_path = Path(servers_dir).expanduser()
    
    servers = []
    for d in sorted(servers_path.iterdir()):
        if d.is_dir() and (d / "server.py").exists():
            server_file = d / "server.py"
            code = server_file.read_text()
            tool_count = code.count("@mcp.tool()")
            
            servers.append({
                "name": d.name.replace("_mcp", ""),
                "path": str(d),
                "tools": tool_count,
            })
    
    return {"success": True, "servers": servers, "total": len(servers)}


@mcp.tool()
async def get_server_tools(
    server_name: str = Field(..., description="Server name"),
    servers_dir: str = Field("~/Desktop/mcp-servers", description="Servers directory"),
) -> dict[str, Any]:
    """Get list of tools in a specific server."""
    import re
    
    servers_path = Path(servers_dir).expanduser()
    server_file = servers_path / f"{server_name}_mcp" / "server.py"
    
    if not server_file.exists():
        return {"success": False, "error": f"Server not found: {server_name}"}
    
    code = server_file.read_text()
    
    # Extract tool names
    tool_pattern = r'async def (\w+)\([^)]*\) -> dict'
    tools = re.findall(tool_pattern, code)
    
    return {
        "success": True,
        "server": server_name,
        "tools": tools,
        "count": len(tools),
    }


if __name__ == "__main__":
    mcp.run()
