"""Documentation Auto-Generator for certified tools."""

from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

from helpermcp.core import DiscoveryResult, ExtractedTool, GeneratedMCPServer


class DocsGenerator:
    """
    Generates documentation for certified MCP tools.
    
    Outputs:
    - usage_guide.md per tool
    - README.md for the server
    - API reference
    """

    def __init__(self):
        # Find templates directory
        templates_dir = Path(__file__).parent.parent / "templates"
        self.env = Environment(
            loader=FileSystemLoader(str(templates_dir)),
            autoescape=select_autoescape(["html", "xml"]),
        )

    def generate_usage_guide(
        self,
        tool: ExtractedTool,
        discovery: DiscoveryResult,
        output_dir: Path,
    ) -> Path:
        """
        Generate usage_guide.md for a single tool.
        
        Returns:
            Path to generated file
        """
        template = self.env.get_template("usage_guide.md.j2")
        
        # Prepare template context
        context = {
            "tool": self._prepare_tool_context(tool),
            "auth_env_var": discovery.auth_env_var or f"{discovery.target_name.upper()}_API_KEY",
        }
        
        content = template.render(**context)
        
        # Write to output
        docs_dir = output_dir / "docs"
        docs_dir.mkdir(parents=True, exist_ok=True)
        
        output_file = docs_dir / f"{tool.name}_guide.md"
        output_file.write_text(content)
        
        return output_file

    def generate_server_readme(
        self,
        server: GeneratedMCPServer,
        discovery: DiscoveryResult,
        output_dir: Path,
    ) -> Path:
        """
        Generate README.md for the MCP server.
        """
        content = f"""# {server.service_name} MCP Server

Auto-generated by HelperMCP with **{server.tools_count}** certified tools.

## Installation

```bash
cd {server.package_name}
pip install -e .
```

## Configuration

Set your API key:
```bash
export {discovery.auth_env_var} = "your-api-key"
```

## Usage

```bash
# Run the MCP server
{server.package_name}

# Or via Python
python -m {server.package_name}.server
```

## Tools

| Tool | Score | Description |
|------|-------|-------------|
"""
        
        for tool in server.tools:
            score = tool.detailed_score.aggregate if tool.detailed_score else tool.score
            content += f"| `{tool.name}` | {score:.1f}/10 | {tool.description[:50]}... |\n"
        
        content += f"""
## Scoring Breakdown

Each tool was evaluated on:
- **LLM Utility** (40%): Can the LLM do this internally?
- **Determinism** (35%): Is output reliable and parsable?
- **Token Efficiency** (25%): Data density vs noise

Only tools with aggregate score **≥7.5** are included.

## Requirements

```
{chr(10).join(server.requirements)}
```

---
*Generated by HelperMCP*
"""
        
        output_file = output_dir / "README.md"
        output_file.write_text(content)
        
        return output_file

    def generate_all_docs(
        self,
        server: GeneratedMCPServer,
        discovery: DiscoveryResult,
        output_dir: Path,
    ) -> list[Path]:
        """
        Generate all documentation for a server.
        
        Returns:
            List of generated file paths
        """
        output_dir = Path(output_dir)
        generated = []
        
        # Generate README
        readme = self.generate_server_readme(server, discovery, output_dir)
        generated.append(readme)
        
        # Generate per-tool guides
        for tool in server.tools:
            if tool.certified:
                guide = self.generate_usage_guide(tool, discovery, output_dir)
                generated.append(guide)
        
        return generated

    def _prepare_tool_context(self, tool: ExtractedTool) -> dict[str, Any]:
        """Prepare tool for template rendering."""
        params = []
        for p in tool.parameters:
            type_map = {
                "string": "str",
                "integer": "int",
                "float": "float",
                "boolean": "bool",
                "array": "list",
                "object": "dict",
            }
            type_hint = type_map.get(p.type.value if hasattr(p.type, 'value') else str(p.type), "str")
            
            params.append({
                "name": p.name,
                "type_hint": type_hint,
                "description": p.description,
                "required": p.required,
                "examples": p.examples,
            })
        
        return {
            "name": tool.name,
            "display_name": tool.display_name,
            "description": tool.description,
            "intent": tool.intent,
            "parameters": params,
            "detailed_score": tool.detailed_score,
            "certification_attempts": tool.certification_attempts,
        }
