"""Documentation Site Generator - Auto-generate Markdown documentation."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader

from helpermcp.core import GeneratedMCPServer, settings
from helpermcp.registry import RegistryDatabase, ToolManifest


class SiteGenerator:
    """
    Generates a complete documentation site from tool manifests.
    
    Output structure:
    docs/
    ├── index.md           # Overview + tool index
    ├── tools/
    │   ├── tool_name.md   # Per-tool reference
    │   └── ...
    ├── services/
    │   ├── stripe.md      # Per-service page
    │   └── ...
    └── troubleshooting.md # Common errors
    """

    def __init__(self, output_dir: Path | None = None):
        self.output_dir = output_dir or settings.output_dir / "docs"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_site(self, registry: RegistryDatabase) -> list[Path]:
        """Generate complete documentation site."""
        generated = []
        
        tools = registry.list_tools(certified_only=True)
        stats = registry.get_stats()
        
        # Group tools by service
        by_service: dict[str, list[ToolManifest]] = {}
        for tool in tools:
            by_service.setdefault(tool.service_name, []).append(tool)
        
        # Generate index
        index_path = self._generate_index(tools, stats, list(by_service.keys()))
        generated.append(index_path)
        
        # Generate tool directory
        (self.output_dir / "tools").mkdir(exist_ok=True)
        for tool in tools:
            tool_path = self._generate_tool_page(tool)
            generated.append(tool_path)
        
        # Generate service pages
        (self.output_dir / "services").mkdir(exist_ok=True)
        for service, service_tools in by_service.items():
            service_path = self._generate_service_page(service, service_tools)
            generated.append(service_path)
        
        # Generate troubleshooting
        troubleshoot = self._generate_troubleshooting(tools)
        generated.append(troubleshoot)
        
        return generated

    def _generate_index(
        self,
        tools: list[ToolManifest],
        stats: dict[str, Any],
        services: list[str],
    ) -> Path:
        """Generate index.md."""
        content = f"""# SuperMCP Tool Registry

> **{stats['certified_tools']}** certified tools across **{stats['services']}** services

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Quick Stats

| Metric | Value |
|--------|-------|
| Total Tools | {stats['total_tools']} |
| Certified | {stats['certified_tools']} |
| Updates Pending | {stats['updates_pending']} |
| Services | {stats['services']} |

## Services

"""
        for service in sorted(services):
            content += f"- [{service}](services/{service.lower()}.md)\n"
        
        content += "\n## All Tools\n\n"
        content += "| Tool | Service | Score | Description |\n"
        content += "|------|---------|-------|-------------|\n"
        
        for tool in sorted(tools, key=lambda t: t.aggregate_score, reverse=True)[:50]:
            desc = tool.description[:50] + "..." if len(tool.description) > 50 else tool.description
            content += f"| [{tool.name}](tools/{tool.name}.md) | {tool.service_name} | {tool.aggregate_score:.1f} | {desc} |\n"
        
        content += "\n---\n*Auto-generated by HelperMCP*\n"
        
        path = self.output_dir / "index.md"
        path.write_text(content)
        return path

    def _generate_tool_page(self, tool: ToolManifest) -> Path:
        """Generate per-tool reference page."""
        params = json.loads(tool.parameters_json)
        
        content = f"""# {tool.display_name}

> Service: **{tool.service_name}** | Score: **{tool.aggregate_score:.1f}/10** | Certified: {'✅' if tool.certified else '❌'}

{tool.description}

"""
        if tool.intent:
            content += f"**Intent**: {tool.intent}\n\n"
        
        # Scoring breakdown
        content += """## Scoring

| Dimension | Score | Weight |
|-----------|-------|--------|
"""
        content += f"| LLM Utility | {tool.llm_utility:.1f} | 40% |\n"
        content += f"| Determinism | {tool.determinism:.1f} | 35% |\n"
        content += f"| Token Efficiency | {tool.token_efficiency:.1f} | 25% |\n"
        content += f"| **Aggregate** | **{tool.aggregate_score:.1f}** | |\n\n"
        
        # Parameters
        if params:
            content += "## Parameters\n\n"
            content += "| Name | Type | Required | Description |\n"
            content += "|------|------|----------|-------------|\n"
            for p in params:
                req = "Yes" if p.get("required", True) else "No"
                content += f"| `{p['name']}` | `{p['type']}` | {req} | {p.get('description', '')} |\n"
            content += "\n"
        
        # API details
        if tool.api_endpoint:
            content += "## API Details\n\n"
            content += f"- **Endpoint**: `{tool.http_method or 'GET'} {tool.api_endpoint}`\n"
            if tool.source_url:
                content += f"- **Documentation**: [{tool.source_url}]({tool.source_url})\n"
            content += "\n"
        
        # Troubleshooting
        if tool.failure_history:
            content += "## Troubleshooting\n\n"
            content += "Recent issues encountered during testing:\n\n"
            for failure in tool.failure_history[-5:]:
                if isinstance(failure, dict):
                    content += f"- **{failure.get('timestamp', 'Unknown')}**: {failure.get('message', 'Unknown error')}\n"
                else:
                    content += f"- {failure}\n"
            content += "\n"
        
        # Example usage
        content += f"""## Example Usage

```python
result = await mcp.call_tool("{tool.name}", {{
"""
        for p in params[:3]:
            content += f'    "{p["name"]}": "...",\n'
        content += "})\n```\n"
        
        content += "\n---\n*Auto-generated by HelperMCP*\n"
        
        path = self.output_dir / "tools" / f"{tool.name}.md"
        path.write_text(content)
        return path

    def _generate_service_page(
        self,
        service: str,
        tools: list[ToolManifest],
    ) -> Path:
        """Generate per-service page."""
        content = f"""# {service} Integration

**{len(tools)}** certified tools available

## Tools

| Tool | Score | Description |
|------|-------|-------------|
"""
        for tool in sorted(tools, key=lambda t: t.aggregate_score, reverse=True):
            content += f"| [{tool.name}](../tools/{tool.name}.md) | {tool.aggregate_score:.1f} | {tool.description[:60]}... |\n"
        
        content += f"""
## Quick Start

```bash
# Set your API key
export {service.upper()}_API_KEY="your-key"

# Use via MCP
python -c "from supermcp import mcp; print(mcp.list_tools())"
```

---
*Auto-generated by HelperMCP*
"""
        
        path = self.output_dir / "services" / f"{service.lower()}.md"
        path.write_text(content)
        return path

    def _generate_troubleshooting(self, tools: list[ToolManifest]) -> Path:
        """Generate troubleshooting guide from failure history."""
        content = """# Troubleshooting Guide

Common issues and solutions for SuperMCP tools.

## General Issues

### Authentication Errors

| Error | Cause | Solution |
|-------|-------|----------|
| `401 Unauthorized` | Invalid API key | Check environment variable is set correctly |
| `403 Forbidden` | Insufficient permissions | Verify API key has required scopes |

### Connection Issues

| Error | Cause | Solution |
|-------|-------|----------|
| `Connection refused` | Service unavailable | Check service status, retry later |
| `Timeout` | Slow network | Increase timeout, check connectivity |

## Tool-Specific Issues

"""
        # Collect failures from all tools
        all_failures = []
        for tool in tools:
            for failure in tool.failure_history:
                if isinstance(failure, dict):
                    all_failures.append({
                        "tool": tool.name,
                        "message": failure.get("message", "Unknown"),
                        "timestamp": failure.get("timestamp", ""),
                    })
        
        if all_failures:
            content += "| Tool | Error | Recent |\n"
            content += "|------|-------|--------|\n"
            for f in all_failures[-20:]:
                content += f"| `{f['tool']}` | {f['message'][:50]}... | {f['timestamp'][:10]} |\n"
        else:
            content += "*No tool-specific failures recorded.*\n"
        
        content += "\n---\n*Auto-generated by HelperMCP*\n"
        
        path = self.output_dir / "troubleshooting.md"
        path.write_text(content)
        return path

    def generate_manifest_json(
        self,
        server: GeneratedMCPServer,
        output_path: Path,
    ) -> Path:
        """Generate manifest.json for a server."""
        manifest = {
            "name": server.package_name,
            "service": server.service_name,
            "version": "1.0.0",
            "generated_at": server.generated_at.isoformat(),
            "tools_count": server.tools_count,
            "tools": [
                {
                    "name": tool.name,
                    "display_name": tool.display_name,
                    "description": tool.description,
                    "score": tool.score,
                    "certified": tool.certified,
                    "parameters": [
                        {
                            "name": p.name,
                            "type": p.type.value if hasattr(p.type, 'value') else str(p.type),
                        }
                        for p in tool.parameters
                    ],
                }
                for tool in server.tools
            ],
        }
        
        output_path.write_text(json.dumps(manifest, indent=2))
        return output_path
